apiVersion: v1
kind: Secret
metadata:
  name: webapp-secrets
type: Opaque
data:
  OPENAI_API_KEY: c2stcHJvai1OYXRzN1I5cEF6QnZOTHA1N2tmeWVKUFM3aVljRURBVmtYUXpxTWM0cW1MYVIySW8yTm1nNzMwNFdUT18tTGtBUTQ1aVhXaWx6QVQzQmxia0ZKa3ZVZXZ6S3JPNGtKc2IyWG1DMXljRU94LUpfQi1vMDIyWjZnekRteV9fTE5SajZPRGtnOEt4R3JrUDVVb3hkS3Bnclh6T0ppa0E=
  LANGCHAIN_API_KEY: bHN2Ml9wdF9jOWQzNWFlZTI3Nzc0YWM2YTI2ZTRhZjAyNWZkMjNmMl9iNGFmZDBlZDFm