name: Terraform Provisioning

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: What do you want to do?
        options: [apply, destroy, plan]
        default: apply
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  terraform_test:
    runs-on: ubuntu-latest

    steps:
      #1. Checkout repo
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{  secrets.AZURE_CREDENTIALS  }}  

      - name: Export Terraform Env Vars
        run: |
          echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with: 
          terraform_version: 1.13.3
      

      
      - name: Terraform Init
        run: terraform init -reconfigure
          
        #Commit to main branch 
      - name: Terraform Plan (apply Path)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform plan -out=tfplan

      - name: Terraform Plan (apply Path)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan

        #Plan the deployment "dry run"
      - name: Terraform Plan Dry Run
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action=='plan'
        run: terraform plan -no-color

        #apply the deployment
      - name: Terraform Plan (Manual Apply)
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action=='apply'
        run: terraform plan -out=tfplan

      - name: Terraform Apply (Manual Apply)
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply'
        run: terraform apply -auto-approve tfplan

        #destroy the deployment
      - name: Terraform Plan (Manual Destroy)
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy'
        run: terraform plan -destroy -out=tfplan

      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy'
        run: terraform apply -auto-approve tfplan

  k8s_spin:
    needs: terraform_test

    runs-on: ubuntu-latest
    steps:
      #1. Checkout repo
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{  secrets.AZURE_CREDENTIALS  }}  

